# Generated by Django 2.2.4 on 2019-11-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
